Preprocessing

In [37]:
import pandas as pd
import re

In [150]:
# Create an index on id
def create_index(reg_no):
    reg_string = str(reg_no)
    return re.sub('\W+','', reg_string)

def clean_metadata(name):
    df = pd.read_csv(name)
    print("Original length: " + str(len(df)))
    df["id"] = df.apply(lambda row: create_index(row['Reg number']), axis=1)
    df.drop_duplicates(inplace=True)
    df.dropna(subset=['Image'], inplace=True)
    print("Final length: " + str(len(df)))
    return df

In [42]:
gandhara = "collections-22-02-20-12_52_28-gandhara.csv"
gandhara_df = clean_metadata(gandhara)
gandhara_df.to_csv("gandhara.csv")

Original length: 196
Final length: 196

In [53]:
# Extract gandharan IDs to ensure no duplication in Buddha dataset
gandhara_ids = set(gandhara_df['id'])

In [86]:
buddha = "buddha_unfiltered.csv"
buddha_df = clean_metadata(buddha)

Original length: 479
Final length: 479

In [110]:
def excludes_words(string, word_list):
    word_set = set(word_list)
    str_set = set(str(string).replace(" ", "").split(";"))
    return word_set.isdisjoint(str_set)

In [111]:
# By changing the second input to exclude-words, we can remove objects that match certain descriptions while leaving everything else intact.

buddha_filtered = buddha_df[~buddha_df.id.isin(gandhara_ids)]
buddha_filtered = buddha_filtered[buddha_filtered["Materials"].apply(lambda t: excludes_words(t, ["copper", "paper"]))]
buddha_filtered = buddha_filtered[buddha_filtered["Object type"].apply(lambda t: excludes_words(t, ["coin", "wall-painting", "amulet-box"]))]
buddha_filtered

,Image,Object type,Museum number,Title,Denomination,Escapement,Description,Producer name,School/style,State,...,Acq notes (acq),Acq notes (exc),Dept,BM/Big number,Reg number,Add ids,Cat no,Banknote serial number,Joined objects,id
1,https://media.britishmuseum.org/media/Reposito...,artefact,"No: 1887,0717.144",NaN,NaN,NaN,Conical spirals representing the curled hair o...,NaN,NaN,NaN,...,NaN,NaN,Asia,NaN,"1887,0717.144",NaN,NaN,NaN,NaN,18870717144
2,https://media.britishmuseum.org/media/Reposito...,base,"No: 1892,0801.11",NaN,NaN,NaN,"Corner of a carved base with part of a foot, p...",NaN,NaN,NaN,...,NaN,NaN,Asia,NaN,"1892,0801.11",NaN,NaN,NaN,NaN,1892080111
3,https://media.britishmuseum.org/media/Reposito...,base,"No: 1890,1116.1",The Hashtnagar Pedestal (Object),NaN,NaN,"Carved image base, inscribed with a date in th...",NaN,NaN,NaN,...,Originally received in the Department of Coins...,NaN,Asia,NaN,"1890,1116.1",NaN,NaN,NaN,NaN,189011161
4,https://media.britishmuseum.org/media/Reposito...,base,"No: 1902,1002.17",NaN,NaN,NaN,"Carved base with an indistinct foot, probably ...",NaN,NaN,NaN,...,NaN,NaN,Asia,NaN,"1902,1002.17",NaN,NaN,NaN,NaN,1902100217
5,https://media.britishmuseum.org/media/Reposito...,block,"No: 1880,0709.40",NaN,NaN,NaN,A rectangular slab carved in limestone ('Palna...,NaN,NaN,NaN,...,Acquired as the result of the abolition in 187...,NaN,Asia,NaN,"1880,0709.40",Miscellaneous number: Elliot no 98,NaN,NaN,NaN,1880070940
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
462,https://media.britishmuseum.org/media/Reposito...,votive panel; 木板畫,No: MAS.459,NaN,NaN,NaN,"Rectangular votive panel with a pointed top, s...",NaN,NaN,NaN,...,The 1917-11-28 group (with MAS numbering) refe...,NaN,Asia,NaN,MAS.459,Miscellaneous number: F.II.iii.2 (Stein no.),NaN,NaN,NaN,MAS459
463,https://media.britishmuseum.org/media/Reposito...,votive panel; 木板畫,"No: 1907,1111.68",NaN,NaN,NaN,Rectangular votive panel painted on both sides...,NaN,NaN,NaN,...,The 1907-11-11 group refers to objects from St...,NaN,Asia,NaN,"1907,1111.68",Miscellaneous number: D.IV.5 (Stein no.),NaN,NaN,NaN,1907111168
464,https://media.britishmuseum.org/media/Reposito...,votive panel; 木板畫,"No: 1907,1111.72",NaN,NaN,NaN,Rectangular votive panel painted on both sides...,NaN,NaN,NaN,...,The 1907-11-11 group refers to objects from St...,NaN,Asia,NaN,"1907,1111.72",Miscellaneous number: D.X.3 (Stein no.),NaN,NaN,NaN,1907111172
465,https://media.britishmuseum.org/media/Reposito...,votive panel; 木板畫,"No: 1907,1111.73",NaN,NaN,NaN,Rectangular votive panel painted on one side. ...,NaN,NaN,NaN,...,The 1907-11-11 group refers to objects from St...,NaN,Asia,NaN,"1907,1111.73",Miscellaneous number: D.X.4 (Stein no.),NaN,NaN,NaN,1907111173
466,https://media.britishmuseum.org/media/Reposito...,votive plaque,"No: As1864,1201.7",NaN,NaN,NaN,Fragment of two rejoined parts of a buff clay ...,NaN,NaN,NaN,...,Book of Presents [512]: Department of Oriental...,NaN,Asia,NaN,"As1864,1201.7",NaN,NaN,NaN,NaN,As186412017

In [117]:
buddha_filtered["id"].is_unique

True

In [104]:
buddha_filtered.to_csv("buddha.csv")

In [151]:
greek = "greek_unfiltered.csv"
greek_df = clean_metadata(greek)

Original length: 651
Final length: 651

In [170]:
# By changing the second input to exclude-words, we can remove objects that match certain descriptions while leaving everything else intact.

greek_filtered = greek_df[~greek_df.id.isin(gandhara_ids)]
greek_filtered = greek_filtered[greek_filtered["Materials"].apply(lambda t: excludes_words(t, ["copper", "paper", "pottery"]))]
greek_filtered = greek_filtered[greek_filtered["Object type"].apply(lambda t: excludes_words(t, ["coin", "finger-ring", "flask", "goblet"]))]
greek_filtered

,Image,Object type,Museum number,Title,Denomination,Escapement,Description,Producer name,School/style,State,...,Acq notes (acq),Acq notes (exc),Dept,BM/Big number,Reg number,Add ids,Cat no,Banknote serial number,Joined objects,id
0,https://media.britishmuseum.org/media/Reposito...,altar; base,"No: 1816,0610.330",NaN,NaN,NaN,Fragment from angle of Parian marble small alt...,NaN,NaN,NaN,...,NaN,NaN,Greek and Roman,NaN,"1816,0610.330",NaN,NaN,NaN,NaN,18160610330
1,https://media.britishmuseum.org/media/Reposito...,amphora,"No: 1895,1020.2",NaN,NaN,NaN,Miniature terracotta flask.\r\nAn amphoriskos ...,NaN,NaN,NaN,...,NaN,NaN,Greek and Roman,NaN,"1895,1020.2",NaN,NaN,NaN,NaN,189510202
5,https://media.britishmuseum.org/media/Reposito...,amulet; figure,No: null,NaN,NaN,NaN,Mould-made amuletic figure in glazed compositi...,NaN,NaN,NaN,...,NaN,Excavated: 1884-1885. Donated by Egypt Explora...,External,NaN,NaN,"Miscellaneous number: 9,9,86,76 (Accession Num...",NaN,NaN,NaN,nan
6,https://media.britishmuseum.org/media/Reposito...,amulet; figure,No: null,NaN,NaN,NaN,Mould-made amuletic figure in glazed compositi...,NaN,NaN,NaN,...,NaN,NaN,External,NaN,NaN,Miscellaneous number: H1051.2 (Accession Number),NaN,NaN,NaN,nan
7,https://media.britishmuseum.org/media/Reposito...,amulet; figure,No: null,NaN,NaN,NaN,Solid cast amuletic figure of human-shaped god...,NaN,NaN,NaN,...,NaN,Excavated in 1884. Donated by Egypt Exploratio...,External,NaN,NaN,Miscellaneous number: H1034.1 (Accession Number),NaN,NaN,NaN,nan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
646,https://media.britishmuseum.org/media/Reposito...,vessel-stamp,No: null,NaN,NaN,NaN,"Egyptian terracotta circular stamp, sometimes ...",NaN,NaN,NaN,...,NaN,Excavated: 1884-1885. EEF 1886,External,NaN,NaN,Miscellaneous number: AN1886.517 (Accession Nu...,NaN,NaN,NaN,nan
647,https://media.britishmuseum.org/media/Reposito...,vessel-stamp,No: null,NaN,NaN,NaN,"Egyptian terracotta circular stamp, sometimes ...",NaN,NaN,NaN,...,NaN,Excavated: 1884-1885. EEF 1886,External,NaN,NaN,Miscellaneous number: AN1886.513 (Accession Nu...,NaN,NaN,NaN,nan
648,https://media.britishmuseum.org/media/Reposito...,vessel-stamp,No: null,NaN,NaN,NaN,"Egyptian terracotta circular stamp, sometimes ...",NaN,NaN,NaN,...,NaN,Excavated 1884-1885. 1885: excavated by Willia...,External,NaN,NaN,Miscellaneous number: 86.666 (Accession Number...,NaN,NaN,NaN,nan
649,https://media.britishmuseum.org/media/Reposito...,vessel-stamp,"No: 1965,0930.895",NaN,NaN,NaN,Fragment of a terracotta stamp. There is no ha...,NaN,NaN,NaN,...,Previously unregistered.,NaN,Greek and Roman,NaN,"1965,0930.895",NaN,NaN,NaN,NaN,19650930895
650,https://media.britishmuseum.org/media/Reposito...,votive figure,No: EA27333,NaN,NaN,NaN,Hollow terracotta figure of Harpocratis in a l...,NaN,NaN,NaN,...,NaN,NaN,Egypt and Sudan,EA27333,"1896,0330.2",NaN,NaN,NaN,NaN,189603302

In [171]:
# There are some items in the greek collection that are without ids. I assign them random ones here.

def make_ids(index):
    return "greek" + str(index)

greek_filtered.reset_index(inplace=True)
greek_filtered['id'] = greek_filtered.apply(lambda row: make_ids(row["index"]) if row['id'] == 'nan' else row['id'], axis=1)
greek_filtered

,index,Image,Object type,Museum number,Title,Denomination,Escapement,Description,Producer name,School/style,...,Acq notes (acq),Acq notes (exc),Dept,BM/Big number,Reg number,Add ids,Cat no,Banknote serial number,Joined objects,id
0,0,https://media.britishmuseum.org/media/Reposito...,altar; base,"No: 1816,0610.330",NaN,NaN,NaN,Fragment from angle of Parian marble small alt...,NaN,NaN,...,NaN,NaN,Greek and Roman,NaN,"1816,0610.330",NaN,NaN,NaN,NaN,18160610330
1,1,https://media.britishmuseum.org/media/Reposito...,amphora,"No: 1895,1020.2",NaN,NaN,NaN,Miniature terracotta flask.\r\nAn amphoriskos ...,NaN,NaN,...,NaN,NaN,Greek and Roman,NaN,"1895,1020.2",NaN,NaN,NaN,NaN,189510202
2,5,https://media.britishmuseum.org/media/Reposito...,amulet; figure,No: null,NaN,NaN,NaN,Mould-made amuletic figure in glazed compositi...,NaN,NaN,...,NaN,Excavated: 1884-1885. Donated by Egypt Explora...,External,NaN,NaN,"Miscellaneous number: 9,9,86,76 (Accession Num...",NaN,NaN,NaN,greek5
3,6,https://media.britishmuseum.org/media/Reposito...,amulet; figure,No: null,NaN,NaN,NaN,Mould-made amuletic figure in glazed compositi...,NaN,NaN,...,NaN,NaN,External,NaN,NaN,Miscellaneous number: H1051.2 (Accession Number),NaN,NaN,NaN,greek6
4,7,https://media.britishmuseum.org/media/Reposito...,amulet; figure,No: null,NaN,NaN,NaN,Solid cast amuletic figure of human-shaped god...,NaN,NaN,...,NaN,Excavated in 1884. Donated by Egypt Exploratio...,External,NaN,NaN,Miscellaneous number: H1034.1 (Accession Number),NaN,NaN,NaN,greek7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
539,646,https://media.britishmuseum.org/media/Reposito...,vessel-stamp,No: null,NaN,NaN,NaN,"Egyptian terracotta circular stamp, sometimes ...",NaN,NaN,...,NaN,Excavated: 1884-1885. EEF 1886,External,NaN,NaN,Miscellaneous number: AN1886.517 (Accession Nu...,NaN,NaN,NaN,greek646
540,647,https://media.britishmuseum.org/media/Reposito...,vessel-stamp,No: null,NaN,NaN,NaN,"Egyptian terracotta circular stamp, sometimes ...",NaN,NaN,...,NaN,Excavated: 1884-1885. EEF 1886,External,NaN,NaN,Miscellaneous number: AN1886.513 (Accession Nu...,NaN,NaN,NaN,greek647
541,648,https://media.britishmuseum.org/media/Reposito...,vessel-stamp,No: null,NaN,NaN,NaN,"Egyptian terracotta circular stamp, sometimes ...",NaN,NaN,...,NaN,Excavated 1884-1885. 1885: excavated by Willia...,External,NaN,NaN,Miscellaneous number: 86.666 (Accession Number...,NaN,NaN,NaN,greek648
542,649,https://media.britishmuseum.org/media/Reposito...,vessel-stamp,"No: 1965,0930.895",NaN,NaN,NaN,Fragment of a terracotta stamp. There is no ha...,NaN,NaN,...,Previously unregistered.,NaN,Greek and Roman,NaN,"1965,0930.895",NaN,NaN,NaN,NaN,19650930895
543,650,https://media.britishmuseum.org/media/Reposito...,votive figure,No: EA27333,NaN,NaN,NaN,Hollow terracotta figure of Harpocratis in a l...,NaN,NaN,...,NaN,NaN,Egypt and Sudan,EA27333,"1896,0330.2",NaN,NaN,NaN,NaN,189603302

In [174]:
greek_filtered['id'].value_counts()

greek370        1
19170701125     1
191104161       1
greek76         1
18591226184     1
               ..
1907051949      1
188604011566    1
1907051945      1
19040204397     1
18561004152     1
Name: id, Length: 543, dtype: int64

In [173]:
greek_filtered = greek_filtered.drop_duplicates(subset=["id"], keep="first")

In [175]:
greek_filtered.to_csv("greek.csv")